name: Python CI/CD DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-lint-security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest bandit

      - name: Run Flake8 (Linting)
        run: |
          flake8 .

      - name: Run Pytest (Unit Tests)
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Run Bandit (Security Analysis)
        run: |
          bandit -r .
